### ISSUE TITLE
Issue running ethzasl_sensor_fusion

### ISSUE THREAD

**Issue by alek-b** [ethz-asl/ethzasl_sensor_fusion#10]
Dear Stephan,
we are trying to run the ethz asl sensor fusion together with asctec mav framework, using the Asctec Pelican as UAV, but something goes wrong :)

We have created a publisher that publishes the 3D position (PoseWithCovarianceStamped) of the UAV within a topic called MULTI_measurement. (this publisher right now provides position data only from one sensor).
Concerning the UAV we applied the patch to the mastermind kernel in order to remove the limitation of the serial port.

Regarding the asctec mav framework this is our fcu_parameters.yaml:

serial_port:            /dev/ttyS2
baudrate:               460800
frame_id:               fcu
packet_rate_imu:        50.0
packet_rate_rc:         20.0
packet_rate_gps:        5.0
packet_rate_ssdk_debug: 10.0
packet_rate_ekf_state:  50.0
max_velocity_xy:        0.5
max_velocity_z:         0.5

state_estimation:       HighLevel_EKF
position_control:       off

and, we defined the following remapping in the ssf_update launch.file (MULTI_sensor.launch).

< launch >
    < node name="position_sensor" pkg="ssf_updates" type="position_sensor" clear_params="true" output="screen" >
        < remap from="/ssf_core/imu_state_input" to="/fcu/imu" / >

```
    < remap from="ssf_core/position_measurement" to="MULTI_measurement" / >

    < rosparam file="$(find ssf_updates)/MULTI_sensor_fix.yaml" / >
< /node>
```

< /launch>

After turning on the UAV and running the MAV framework, we launched the ssf_update with the command provided on the guide: 

roslaunch ssf_updates MULTI_sensor.launch

If we try to init the filter with the dinamic reconfigure gui we got a warning saying that no position has been acquired so the position for the filter initialization is put to zero.

Then if we try to plot the output of the filter with the script plot_relevant we don't get anything.

Just to be sure, we understood that we don't need to directly launch the sss_core, because this should be launched within the ss_update. Is this right?

What's wrong with our setup/remap? Do you have some suggestion in order to fix the problem?

Thanks in advance.

Alessandro

**Comment by stephanweiss** [comment]
Alessandro,

First, you are correct, the ssf_core gets launched with ssf_updates (it is actually a class in ssf_updates) so no need to launch it separately.

Then, it looks like you are nearly there - just a few modifications:

1) ssf_core accepts two messages containing IMU - depending on weather you use the state-propagation on the AscTec hardware or not. In fcu_parameters.yaml "packet_rate_imu" defines the rate a standard IMU message is published. ssf_core uses this IMU data for state propagation. "packet_rate_ekf_state"  sends the IMU data and states propagated on the AscTec hardware to ssf_core where only cov and updates are made.
Now, if you enable both messages (at 50Hz in your case) you confuse the ss_core since it receives two times the IMU data (from "packet_rate_ekf_state" and "packet_rate_imu").
Long story short: if you use the AscTec state propagation (parameter "state_estimation" in the fcu parameters is set to STATE_EST_HIGHLEVEL_EKF), set  packet_rate_imu=0. Otherwise, set packet_rate_ekf_state=0.

2) Topic remapping: so far, you only remap the measurement topic. You have to remap the IMU topic as well (if you do NOT use the AscTec propagation) or you have to remap the "hl_state_input" to "fcu/ekf_state_out" and "correction" to "fcu/ekf_state_in" (if you use the AscTec propagation). Please have a look at pose_sensor.launch in the sample sensor module files. The filter framework only starts reading measurements once it received IMU data - hence the message that no measurement arrived yet in your case. Also, the plots are only updated on measurement rate - so if there are no measurements (or the filter does not yet accept them because of the lack of IMU data as in your case) the plots will not show anything. Alternatively, you can plot yourself the topic [your_sensor}/pose. This is a pose with covariance stamped that is published at IMU rate and can be used for MAV control on non-asctec vehicles.

Let me know if this helped.

Best
Stephan

**Comment by alek-b** [comment]
Hi Stephan,
finally we get the code working! :)
Besides you suggested, we also went wrong with the ty:e of messages: while the publisher used to publish a PositionWithCovarianceStamped, we were listening about a PoseWithCovarianceStamped.

Thanks again

Alessandro

**Comment by stephanweiss** [comment]
Awesome, thanks much for the feedback.
