### ISSUE TITLE
Indexes on H matrix

### ISSUE THREAD

**Issue by alek-b** [ethz-asl/ethzasl_sensor_fusion#16]
Hi Stephan,
I was modifying the default version of position_sensor.cpp, but I was stuck about some indexes that you've used within the H matrix.

On row 128 of position_sensor.cpp, the columns 22-24 of H matrix are used for p_ci

``` ruby
H_old.block<3,3>(0,22) = C_wv.transpose()*C_q.transpose()*state_old.L_; // use "camera"-IMU distance p_ci state here as position_sensor-IMU distance
```

while in state.cpp at row 114, rows 22-24 refers to vectorial part of q_ci. 

``` ruby
state.data[22] = q_ci_.x();
state.data[23] = q_ci_.y();
state.data[24] = q_ci_.z();
state.data[25] = p_ci_[0];
state.data[26] = p_ci_[1];
state.data[27] = p_ci_[2];
```

The same for 

``` ruby
    H_old.block<3,1>(0,15) = C_wv.transpose()*C_q.transpose()*state_old.p_ci_ + C_wv.transpose()*state_old.p_; // L
    H_old.block<3,3>(0,16) = -C_wv.transpose()*skewold; // q_wv
    H_old.block<3,3>(3,16) = Eigen::Matrix<double,3,3>::Identity(); // fix vision world drift q_wv since it does not exist here
    H_old.block<3,3>(6,19) = Eigen::Matrix<double,3,3>::Identity(); // fix "camera"-IMU drift q_ci since it does not exist here
```

Can you help me?

Thanks,

Alessandro

**Comment by stephanweiss** [comment]
Alessandro,

Sorry for the late reply.
What you mention is a funny (or better said unlucky) coincidence:
- the H matrix works in the error state where quaternions are in minimal representation (i.e. 3 elements for the error quaternions)
- state.data contains the full state (i.e. 4 elements for the quaternions). Since we have three quaternions (q, q_vw, _q_ci), the indices for the full state vector are shifted by three

Hope this explanation helps.

Best
Stephan

**Comment by simonlynen** [comment]
@alek-b I assume this is reolved. Feel free to reopen the issue if this is not the case.
